### ISSUE TITLE
URL validation when adding / editing SP or IdP

### ISSUE THREAD

**Issue by korteke** [ausaccessfed/federationregistry#202]
When registering/editing a new Service provider grails? treats this URL endpoint as invalid:
"https://testbench-sp.aero/sp/Shibboleth.sso/SAML2/POST" same thing with the TLD ".dev", but ".aero" and many others works just fine.

Error:
Unable to save when updating assertionconsumerservice:[id:24, location: https://testbench-sp.bank/sp/Shibboleth.sso/SAML2/POST]. Stacktrace follows:
Message: Unable to save when updating assertionconsumerservice:[id:24, location: https://testbench-sp.bank/sp/Shibboleth.sso/SAML2/POST]

```
[ 06.07.15 15:18:00.277] ERROR StackTrace  - Full Stack Trace:
aaf.fr.foundation.ErronousStateException: Unable to save when updating assertionconsumerservice:[id:24, location: https://testbench-sp.bank/sp/Shibboleth.sso/SAML2/POST]
    at aaf.fr.foundation.EndpointService.update(EndpointService.groovy:51)
    at aaf.fr.foundation.DescriptorEndpointController$_closure2.doCall(DescriptorEndpointController.groovy:79)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359)
    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275)
    at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
    at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
    at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344)
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272)
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by korteke** [comment]
And of course the problems is that I am using grails version 2.2.4. Which includes old Apache commons urlvalidator.
Need to check which version includes all the new TLD's.
