### ISSUE TITLE
500 when deleting contact phone numbers

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/federationregistry#203]
Hi,

I had entered a phone number into my contact information - and I then got surprised it got published in the metadata.  So I wanted to remove it...

When trying to remove the phone number (i.e., editing the contact, setting the work phone number field to blank and attempting to save), I got a 500 error.

In the stack trace, I could trace it down to:

```
groovy.lang.MissingMethodException: No signature of method: java.lang.String.delete() is applicable for argument types: () values: []
Possible solutions: center(java.lang.Number), center(java.lang.Number), sleep(long), center(java.lang.Number, java.lang.CharSequence), center(java.lang.Number, java.lang.String), sleep(long, groovy.lang.Closure)
        at aaf.fr.foundation.ContactsController$_closure6.doCall(ContactsController.groovy:167)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
```

and in ContactsController.groovy, I could see:

```
                        if(params.workPhone)
                                if(!contact.workPhone)
                                        contact.workPhone = params.workPhone
                                else
                                        contact.workPhone = params.workPhone
                        else
                                if(contact.workPhone) {
                                        contact.workPhone.delete()
                                        contact.workPhone = null
                                }
```

I'm not sure where the call to .delete() comes from - I think setting to null should do the job, given that these are declared as Strings in Contact.groovy:

```
        String workPhone
        String homePhone
        String mobilePhone
```

So I think the fix would be for all these three fields, remove the .delete() call.

Bradley, any thoughts or explanations?  And happy to accept the proposed fix?  A pull request can follow soon...

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
PS: In the meantime, I have manually fixed this on the console with:

````
import aaf.fr.foundation.*
contact = Contact.findWhere(email:"email@address.com")
println contact
println contact.workPhone
contact.workPhone=null
println contact.workPhone
````
